// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/request.proto

package pipelines

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RequestService service

func NewRequestServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RequestService service

type RequestService interface {
	AddRequest(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error)
}

type requestService struct {
	c    client.Client
	name string
}

func NewRequestService(name string, c client.Client) RequestService {
	return &requestService{
		c:    c,
		name: name,
	}
}

func (c *requestService) AddRequest(ctx context.Context, in *Request, opts ...client.CallOption) (*Request, error) {
	req := c.c.NewRequest(c.name, "RequestService.AddRequest", in)
	out := new(Request)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RequestService service

type RequestServiceHandler interface {
	AddRequest(context.Context, *Request, *Request) error
}

func RegisterRequestServiceHandler(s server.Server, hdlr RequestServiceHandler, opts ...server.HandlerOption) error {
	type requestService interface {
		AddRequest(ctx context.Context, in *Request, out *Request) error
	}
	type RequestService struct {
		requestService
	}
	h := &requestServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RequestService{h}, opts...))
}

type requestServiceHandler struct {
	RequestServiceHandler
}

func (h *requestServiceHandler) AddRequest(ctx context.Context, in *Request, out *Request) error {
	return h.RequestServiceHandler.AddRequest(ctx, in, out)
}
